[package]
name = "practica1"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
csv = "1.3.1"
eframe = "0.31.1"
egui = "0.31.1"
egui_extras = "0.31.1"
rfd = "0.15.3"
serde = {version = "1.0.219", features = ["derive"]}
serde_json = "1.0.140"
